# -*- coding: utf-8 -*-
"""GRU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqikkY64av4BjQiTLmNlk02xEpK9qMDd
"""

from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# =====================
# Load IMDb Dataset
# =====================

vocab_size = 10000

(x_train, y_train), (x_test, y_test) = imdb.load_data(
    num_words=vocab_size
)

# =====================
# Padding Sequences
# =====================

max_words = 500

x_train = pad_sequences(x_train, maxlen=max_words)
x_test = pad_sequences(x_test, maxlen=max_words)

# Validation Set
x_valid = x_train[:5000]
y_valid = y_train[:5000]

x_train = x_train[5000:]
y_train = y_train[5000:]

# =====================
# Build GRU Model
# =====================

model = Sequential([
    Embedding(
        input_dim=vocab_size,
        output_dim=128,
        input_length=max_words
    ),

    GRU(
        units=128,
        dropout=0.3,
        recurrent_dropout=0.3
    ),

    Dense(64, activation='relu'),
    Dropout(0.3),

    Dense(1, activation='sigmoid')
])

# =====================
# Compile Model
# =====================

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
print(model.summary())



# =====================
# Early Stopping
# =====================

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)


# =====================
# Train Model
# =====================

history = model.fit(
    x_train,
    y_train,
    epochs=10  ,
    batch_size=64,
    validation_data=(x_valid, y_valid),
    callbacks=[early_stop],
    verbose=1
)

# =====================
# Evaluate
# =====================

loss, accuracy = model.evaluate(
    x_test,
    y_test,
    verbose=0
)

print("\nTest Accuracy:", accuracy)
print("Test Loss:", loss)

