# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRCEE1poNSxUzKoJ1YrNDuFYq9_1gJ0F
"""

from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Load Dataset
# ===================
vocab_size = 10000

(x_train, y_train), (x_test, y_test) = imdb.load_data(
    num_words=vocab_size
)

# Padding
# ===================
max_words = 500

x_train = pad_sequences(x_train, maxlen=max_words)
x_test = pad_sequences(x_test, maxlen=max_words)

# Validation Split
x_valid = x_train[:5000]
y_valid = y_train[:5000]

x_train = x_train[5000:]
y_train = y_train[5000:]



# Build LSTM Model
# ===================
model = Sequential()

model.add(
    Embedding(
        input_dim=vocab_size,
        output_dim=128,
        input_length=max_words
    )
)

model.add(
    LSTM(
        128,
        dropout=0.3,
        recurrent_dropout=0.3
    )
)

model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(1, activation='sigmoid'))

# Compile
# ===================
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Early Stopping
# ===================
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

# Train
# ===================
history = model.fit(
    x_train,
    y_train,
    epochs=4,
    batch_size=64,
    validation_data=(x_valid, y_valid),
    callbacks=[early_stop],
    verbose=1
)

# Evaluate
# ===================
loss, accuracy = model.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(f"\nTest Accuracy : {accuracy:.4f}")
print(f"Test Loss     : {loss:.4f}")

from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Load Dataset
# ===================
vocab_size = 10000

(x_train, y_train), (x_test, y_test) = imdb.load_data(
    num_words=vocab_size
)

# Padding
# ===================
max_words = 500

x_train = pad_sequences(x_train, maxlen=max_words)
x_test = pad_sequences(x_test, maxlen=max_words)

# Validation Split
x_valid = x_train[:5000]
y_valid = y_train[:5000]

x_train = x_train[5000:]
y_train = y_train[5000:]

# Build LSTM Model
# ===================
model = Sequential()

model.add(
    Embedding(
        input_dim=vocab_size,
        output_dim=128,
        input_length=max_words
    )
)

model.add(
    LSTM(
        128,
        dropout=0.3,
        recurrent_dropout=0.3
    )
)

model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(1, activation='sigmoid'))

# Compile
# ===================
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Early Stopping
# ===================
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

# Train
# ===================
history = model.fit(
    x_train,
    y_train,
    epochs=3,
    batch_size=64,
    validation_data=(x_valid, y_valid),
    callbacks=[early_stop],
    verbose=1
)

# Evaluate
# ===================
loss, accuracy = model.evaluate(
    x_test,
    y_test,
    verbose=0
)

print(f"\nTest Accuracy : {accuracy:.4f}")
print(f"Test Loss     : {loss:.4f}")

